package funkycompiler

import stage3.*

object stdlib extends StdLibVariables with StdLibFunctions

trait StdLibVariables:
  val Pitch                 = Variable("Pitch")
  val Roll                  = Variable("Roll")
  val Yaw                   = Variable("Yaw")
  val Trim                  = Variable("Trim")
  val VTOL                  = Variable("VTOL")
  val Throttle              = Variable("Throttle")
  val Altitude              = Variable("Altitude")
  val AltitudeAgl           = Variable("AltitudeAgl")
  val GS                    = Variable("GS")
  val IAS                   = Variable("IAS")
  val TAS                   = Variable("TAS")
  val Fuel                  = Variable("Fuel")
  val AngleOfAttack         = Variable("AngleOfAttack")
  val AngleOfSlip           = Variable("AngleOfSlip")
  val PitchAngle            = Variable("PitchAngle")
  val RollAngle             = Variable("RollAngle")
  val Heading               = Variable("Heading")
  val Time                  = Variable("Time")
  val GForce                = Variable("GForce")
  val VerticalG             = Variable("VerticalG")
  val Latitude              = Variable("Latitude")
  val Longitude             = Variable("Longitude")
  val PitchRate             = Variable("PitchRate")
  val RollRate              = Variable("RollRate")
  val YawRate               = Variable("YawRate")
  val LandingGear           = Variable("LandingGear")
  val TargetHeading         = Variable("TargetHeading")
  val TargetElevation       = Variable("TargetElevation")
  val TargetDistance        = Variable("TargetDistance")
  val Brake                 = Variable("Brake")
  val GearDown              = Variable("GearDown")
  val FireGuns              = Variable("FireGuns")
  val FireWeapons           = Variable("FireWeapons")
  val LaunchCountermeasures = Variable("LaunchCountermeasures")
  val Activate1             = Variable("Activate1")
  val Activate2             = Variable("Activate2")
  val Activate3             = Variable("Activate3")
  val Activate4             = Variable("Activate4")
  val Activate5             = Variable("Activate5")
  val Activate6             = Variable("Activate6")
  val Activate7             = Variable("Activate7")
  val Activate8             = Variable("Activate8")
  val TargetSelected        = Variable("TargetSelected")
  val SelectedWeapon        = Variable("SelectedWeapon")
end StdLibVariables

trait StdLibFunctions:
  val abs           = Function("abs")
  val ceil          = Function("ceil")
  val clamp         = Function("clamp")
  val clamp01       = Function("clamp01")
  val deltaangle    = Function("deltaangle")
  val exp           = Function("exp")
  val floor         = Function("floor")
  val inverselerp   = Function("inverselerp")
  val lerp          = Function("lerp")
  val lerpangle     = Function("lerpangle")
  val lerpunclamped = Function("lerpunclamped")
  val log           = Function("log")
  val log10         = Function("log10")
  val pingpong      = Function("pingpong")
  val max           = Function("max")
  val min           = Function("min")
  val pow           = Function("pow")
  val repeat        = Function("repeat")
  val round         = Function("round")
  val sign          = Function("sign")
  val smoothstep    = Function("smoothstep")
  val sqrt          = Function("sqrt")
  val sin           = Function("sin")
  val cos           = Function("cos")
  val tan           = Function("tan")
  val asin          = Function("asin")
  val acos          = Function("acos")
  val atan          = Function("atan")
  val rate          = Function("rate")
  val sum           = Function("sum")
  val smooth        = Function("smooth")
  val PID           = Function("PID")
  val ammo          = Function("ammo")
end StdLibFunctions
